# Generated by Django 4.1.7 on 2023-03-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('soni', models.IntegerField(default=1)),
                ('tur', models.TimeField(auto_now=True)),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('old_narx', models.IntegerField()),
                ('new_narx', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.mobile_type')),
            ],
        ),
        migrations.CreateModel(
            name='AccesMaxulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.accestype')),
            ],
        ),
    ]
