# Generated by Django 4.1.7 on 2023-03-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesmaxulotlar',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='accesmaxulotlar',
            name='old_price',
        ),
    ]
