# Generated by Django 4.1.7 on 2023-04-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_rename_new_price_accesmaxulotlar_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesMaxulotlar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.accestype')),
            ],
        ),
    ]
