# Generated by Django 4.1.7 on 2023-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_accesmaxulotlar2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuvenirProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
    ]
