# Generated by Django 4.1.7 on 2023-04-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_suvenirproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('new_narx', models.CharField(max_length=30)),
                ('old_narx', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('new_narx', models.CharField(max_length=30)),
                ('old_narx', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
    ]
