# Generated by Django 4.2 on 2023-06-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_aksessuar_gamedevice_keys_notebooks_printers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccesMaxulotlar2',
        ),
    ]
