# Generated by Django 4.2 on 2023-06-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_delete_accesmaxulotlar2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aksessuar',
        ),
        migrations.DeleteModel(
            name='GameDevice',
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
        migrations.DeleteModel(
            name='Notebooks',
        ),
        migrations.DeleteModel(
            name='Printers',
        ),
    ]
