# Generated by Django 4.2 on 2023-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_delete_aksessuar_delete_gamedevice_delete_keys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
    ]
