# Generated by Django 4.2 on 2023-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="input_price",
            field=models.FloatField(verbose_name="kirim narxi"),
        ),
        migrations.AlterField(
            model_name="products",
            name="sell_price",
            field=models.FloatField(verbose_name="sotuv narxi"),
        ),
    ]
